#+TITLE: Vagrant-Digital-Agenda-Scoreboard

* Introduction 

This Vagrant description is for a virtualbox running Centos 6.5,
which has as development environment view of the digital agenda
scoreboard production environment.

This work is done in the context of the Open Data Support project
(https://joinup.ec.europa.eu/community/ods/description).  It will
create a locally deployable instance of the Digital Agenda Software
stack.  With this instance new statistical data can be published as
Linked Data.

Open Data Support is funded under SMART 2012/0107 ‘Lot 2: Provision of
services for the Publication, Access and Reuse of Open Public Data
across the European Union, through existing open data
portals’(Contract No. 30-CE-0530965/00-17).

*WARNING:* Vagrant machines are not secure and are for
 testing/development purposes only. User accounts and passwords will
 need to be updated for any production usage.

* Deployment steps
On the host machine:
  - install virtualbox and vagrant (See Below)
  - check out this git repository,
  - vagrant up (See starting up vagrant below)
On the vagrant machine
  - login to the system

    user account: /vagrant/, password: /vagrant/
    
    *note:* credentials for virtuoso are dba (password to be provided)

  - cd /vagrant
  - Generate the SSL certificate to be used.
    - A good description on how to to this can be found here:
      http://www.akadia.com/services/ssh_test_certificate.html
  - Regenerate the configuration files, etc. using the command:
    - ( autoconf ; ./configure )

  - Install the extra software, build the components and start the various
    services, using the command:

    - sudo scripts/setup.sh

    Once installed there is not requirement to rebuild the 
    system each time and the only the services need to be restarted, using

    - sudo scripts/setup.sh -S

** Installation Setup
The two main components to install are:

- install VirtualBox - 5.0.0 (https://www.virtualbox.org)

- install Vagrant - 1.7.4 (https://www.vagrantup.com/)

Prior versions will not be checked against (sorry).

** Starting up Vagrant
#+BEGIN_SRC bash
vagrant plugin install vagrant-vbguest
    # Which will install the virtualbox guest additions
    # allowing full screen for this virtualbox.
vagrant up
    # Which will make sure the interface is accessible
    # It will download the ISO image, and 
    # then will download all necessary packages
    # 
    # Estimated activation time depends on network download speed, but on a
    # high speed connection is approximately 15 minutes.
   
   # restart the system (ensuring GUI properly accessible)
vagrant halt
vagrant up
#+END_SRC
* Testing Links:

- Tomcat - http://localhost:8080/
- Virtuoso Sparql Endpoint - http://localhost:1111/sparql
- Virtuoso Conductor - http://localhost:8890/
- Apache - http://localhost/
- CR     - http://localhost:8082/data
- Plone  - http://localhost:8440/Plone
- Elda   - http://localhost:8080/scoreboard

All these should also be accessible viaL

- http://www.digital-agenda-data.eu 

which will link to the local machine.

* Problems
- Virtuoso database permissions for CR3USER and CR3ROUSER need to be
  updated via the conductor (giving them administration rights).
- cr-das.war is renamed as data.war so it matches the tomcat path
  required.
- Test description not available.
