#!/bin/sh
start() {
	#restart virtuoso
	cd /var/local/virtuoso/var/lib/virtuoso/ontowiki
	/var/local/virtuoso/bin/virtuoso-t +configfile /var/local/virtuoso/var/lib/virtuoso/ontowiki/virtuoso.ini
}

stop() {
        echo "stop"
	process=`ps ax | grep "[o]ntowiki/virtuoso.ini" | awk '{print $1}'`
	kill -9 $process
}

case "$1" in
 start) start ;;
 stop) stop  ;;
 restart)
	 stop
	 start ;;
 *)
	echo $"Usage: $0 {start|stop|restart}"
	exit 2
esac
exit $?
